version: '3'

services:
  rabbit_mq:
    container_name: rabbit_mq
    image: rabbitmq:3.8.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
